var theData = {
    "main": {
        "title": "大前端",
        "items": [
            {
                "title": "全栈",
                "items": [
                    {
                        "title": "Web 前端",
                        "items": [
                            {
                                "title":"Web前端重构",
                                "items":[
                                    {
                                       "title":"PC端页面",
                                       "items":[
                                            {
                                                "title":"XHTML1.0"
                                            },
                                            {
                                                "title":"CSS2.0"
                                            }
                                       ]
                                    },
                                    {
                                       "title":"M端/H5/M站页面开发",
                                       "items":[
                                            {
                                                "title":"HTML5.0"
                                            },
                                            {
                                                "title":"CSS3.0"
                                            }
                                       ]
                                    }
                                ]
                            },
                            {
                                "title":"JavaScript语言",
                                "items":[
                                    {
                                       "title":"JS初级"
                                    },
                                    {
                                       "title":"JS高级"
                                    },
                                    {
                                       "title":"JS分水岭",
                                       "items":[
                                            {
                                                "title":"面向对象"
                                            },
                                            {
                                                "title":"链式编程"
                                            },
                                            {
                                                "title":"设计模式"
                                            },
                                            {
                                                "title":"闭包"
                                            },
                                            {
                                                "title":"函数式编程"
                                            },
                                            {
                                                "title":"ES6"
                                            },
                                            {
                                                "title":"TypeScript"
                                            }
                                       ]
                                    }
                                ]
                            },
                            {
                                "title":"前端工程化",
                                "items":[
                                    {
                                       "title":"常用工具",
                                    },
                                    {
                                       "title":"开发工具",
                                    },
                                    {
                                       "title":"项目管理",
                                    },
                                    {
                                       "title":"前端集成解决方案",
                                    }
                                ]
                            },
                            {
                                "title":"模块化开发",
                                "items":[
                                ]
                            },
                            {
                                "title":"模板引擎",
                                "items":[
                                ]
                            },
                            {
                                "title":"MVX框架",
                                "items":[
                                    {
                                        "title":"React"
                                    },
                                    {
                                        "title":"Angular"
                                    },
                                    {
                                        "title":"Vue"
                                    }
                                ]
                            },
                            {
                                "title":"其他框架",
                                "items":[
                                    {
                                        "title":"jQuery"
                                    },
                                    {
                                        "title":"Bootstrap"
                                    },
                                    {
                                        "title":"swiper"
                                    },
                                    {
                                        "title":"iscroll"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "title": "Web 后端",
                        "items":[
                            {
                                "title": "Node + Mongoddb",
                                "items": [
                                    {
                                        "title": "Express"
                                    },
                                    {
                                        "title": "koa"
                                    },
                                    {
                                        "title": "socketio"
                                    }
                                ]
                            },
                            {
                                "title":"PHP"
                            },
                            {
                                "title":"JAVA"
                            }
                        ]
                    },
                    {
                        "title": "服务器端",
                        "items":[
                            {
                                "title":"Nginx",
                                "items":[
                                    {
                                        "title":"http升级https"
                                    },
                                    {
                                        "title":"无痛跨域"
                                    },
                                    {
                                        "title":"与单页面路由结合"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            },
            {
                "title": "Web App",
                "items": [
                    {
                        "title":"Native App",
                    },
                    {
                        "title":"Hybrid App",
                        "items":[
                            {
                                "title": "Angular + ionic"
                            },
                            {
                                "title": "React Native"
                            },
                            {
                                "title": "Vue Weex"
                            }
                        ]
                    }
                ]
            },
            {
                "title": "微信开发",
                "items": [
                    {
                        "title": "公众号",
                        "items":[
                            {
                                "title":"工具安装"
                            },
                            {
                                "title":"环境配置"
                            },
                            {
                                "title":"成为开发者"
                            },
                            {
                                "title":"公众号配置"
                            },
                            {
                                "title":"微信API文档"
                            },
                            {
                                "title":"实际运用"
                            }
                        ]
                    },
                    {
                        "title": "小程序",
                        "items":[
                            {
                                "title":"基础搭建"
                            },
                            {
                                "title":"文档结构"
                            },
                            {
                                "title":"语法"
                            },
                            {
                                "title":"地理位置"
                            },
                            {
                                "title":"请求地址"
                            },
                            {
                                "title":"两小时搭建一个小程序"
                            }
                        ]
                    }
                ]
            },
            {
                "title": "大数据",
                "items": [
                    {
                        "title": "大数据架构",
                        "items":[
                            {
                                "title":"可视化应用",
                                "items":[
                                    {
                                        "title":"HightCharts"
                                    },
                                    {
                                        "title":"ECharts"
                                    },
                                    {
                                        "title":"D3"
                                    },
                                    {
                                        "title":"Forge"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "title": "大数据分析",
                        "items":[
                            {
                                "title":"数据库操作",
                                "items":[
                                    {
                                        "title":"Mongodb"
                                    },
                                    {
                                        "title":"MySql"
                                    }
                                ]
                            }
                        ]
                    },
                    {
                        "title": "大数据开发",
                        "items":[
                            {
                                "title":"数据前端开发",
                                "items":[
                                    {
                                        "title":"HightCharts"
                                    },
                                    {
                                        "title":"ECharts"
                                    },
                                    {
                                        "title":"D3"
                                    },
                                    {
                                        "title":"JavaScript"
                                    }
                                ]
                            },
                            {
                                "title":"数据获取",
                                "items":[
                                    {
                                        "title":"HTML"
                                    },
                                    {
                                        "title":"CSS"
                                    },
                                    {
                                        "title":"JavaScript"
                                    },
                                    {
                                        "title":"NodeJs"
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    }
}